# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 608)
        MainWindow.setMinimumSize(QtCore.QSize(800, 608))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 181, 501))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(199, 9, 591, 281))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.spells = QtWidgets.QWidget()
        self.spells.setObjectName("spells")
        self.tabWidget.addTab(self.spells, "")
        self.attacks = QtWidgets.QWidget()
        self.attacks.setObjectName("attacks")
        self.tabWidget.addTab(self.attacks, "")
        self.equipment = QtWidgets.QWidget()
        self.equipment.setObjectName("equipment")
        self.tabWidget.addTab(self.equipment, "")
        self.inv = QtWidgets.QWidget()
        self.inv.setObjectName("inv")
        self.tabWidget.addTab(self.inv, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(199, 299, 591, 261))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 520, 181, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCharacter_Sheets = QtWidgets.QMenu(self.menubar)
        self.menuCharacter_Sheets.setObjectName("menuCharacter_Sheets")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuExport = QtWidgets.QMenu(self.menuTools)
        self.menuExport.setObjectName("menuExport")
        self.menuRecording_2 = QtWidgets.QMenu(self.menubar)
        self.menuRecording_2.setObjectName("menuRecording_2")
        self.menuMacros = QtWidgets.QMenu(self.menubar)
        self.menuMacros.setObjectName("menuMacros")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionNew_2 = QtWidgets.QAction(MainWindow)
        self.actionNew_2.setObjectName("actionNew_2")
        self.actionLoad_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_2.setObjectName("actionLoad_2")
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setObjectName("actionView")
        self.actionMacros = QtWidgets.QAction(MainWindow)
        self.actionMacros.setObjectName("actionMacros")
        self.actionLibrary = QtWidgets.QAction(MainWindow)
        self.actionLibrary.setObjectName("actionLibrary")
        self.actionLoad_3 = QtWidgets.QAction(MainWindow)
        self.actionLoad_3.setObjectName("actionLoad_3")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionLibrary_2 = QtWidgets.QAction(MainWindow)
        self.actionLibrary_2.setObjectName("actionLibrary_2")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionView_2 = QtWidgets.QAction(MainWindow)
        self.actionView_2.setObjectName("actionView_2")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionJekyll_Blog_Post = QtWidgets.QAction(MainWindow)
        self.actionJekyll_Blog_Post.setObjectName("actionJekyll_Blog_Post")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuCharacter_Sheets.addAction(self.actionNew_2)
        self.menuCharacter_Sheets.addAction(self.actionLoad_2)
        self.menuCharacter_Sheets.addAction(self.actionView)
        self.menuExport.addAction(self.actionJekyll_Blog_Post)
        self.menuTools.addAction(self.menuExport.menuAction())
        self.menuRecording_2.addAction(self.actionStart)
        self.menuRecording_2.addAction(self.actionStop)
        self.menuRecording_2.addSeparator()
        self.menuRecording_2.addAction(self.actionLibrary_2)
        self.menuMacros.addAction(self.actionAdd)
        self.menuMacros.addSeparator()
        self.menuMacros.addAction(self.actionView_2)
        self.menuMacros.addAction(self.actionEdit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCharacter_Sheets.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuRecording_2.menuAction())
        self.menubar.addAction(self.menuMacros.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "wDnD"))
        self.label.setText(_translate("MainWindow", "Stats:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spells), _translate("MainWindow", "Spells"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.attacks), _translate("MainWindow", "Attacks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.equipment), _translate("MainWindow", "Equipment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inv), _translate("MainWindow", "Inventory"))
        self.label_2.setText(_translate("MainWindow", "Notes:"))
        self.pushButton.setText(_translate("MainWindow", "Map"))
        self.pushButton_2.setText(_translate("MainWindow", "Player Sheet"))
        self.menuFile.setTitle(_translate("MainWindow", "Campaign"))
        self.menuCharacter_Sheets.setTitle(_translate("MainWindow", "Character Sheets"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuRecording_2.setTitle(_translate("MainWindow", "Recording"))
        self.menuMacros.setTitle(_translate("MainWindow", "Macros"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionNew_2.setText(_translate("MainWindow", "New"))
        self.actionLoad_2.setText(_translate("MainWindow", "Load"))
        self.actionView.setText(_translate("MainWindow", "View"))
        self.actionMacros.setText(_translate("MainWindow", "Macros"))
        self.actionLibrary.setText(_translate("MainWindow", "Library"))
        self.actionLoad_3.setText(_translate("MainWindow", "Load"))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionLibrary_2.setText(_translate("MainWindow", "Library"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionView_2.setText(_translate("MainWindow", "View"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionJekyll_Blog_Post.setText(_translate("MainWindow", "Jekyll Blog Post"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

